# Type 'Metrics' (6):
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false #FIXME: later

Metrics/MethodLength:
  Enabled: false #FIXME: later
  CountComments: false

Metrics/ModuleLength:
  Enabled: false #FIXME: later
  CountComments: false

Metrics/PerceivedComplexity:
  Enabled: false #FIXME: later
