# Type 'Rails' (2):
Rails/FindBy:
  Include:
    - app/models/**/*.rb
    - lib/**/*.rb
    - db/**/*.rb

Rails/FindEach:
  Include:
    - app/models/**/*.rb
    - lib/**/*.rb
    - db/**/*.rb

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/TimeZone:
  EnforcedStyle: strict

Rails/InverseOf:
  Exclude:
    - 'app/models/search_result.rb'
