# Type 'Style' (12):
Style/AndOr:
  EnforcedStyle: conditionals

Style/AutoResourceCleanup:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters: # FIXME: as of 0.52.1, [] is used almost instead of ()
    "%": "()"
    "%i": "()"
    "%q": "()"
    "%Q": "()"
    "%r": "{}"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/Send:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true
  Methods:
    - each_with_object:
      - elem
      - acc

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
