Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'db/schema.rb'

Layout/MultilineAssignmentLayout:
  Exclude:
    - 'lib/oiv_api/client.rb'

Metrics/LineLength:
  Exclude:
    - 'db/schema.rb'
    - 'config/deploy.rb'
    - 'spec/models/category_spec.rb'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Style/Encoding:
  Exclude:
    - 'db/schema.rb'

Style/StructInheritance:
  Exclude:
    - 'app/policies/**/*'
